package dev.tg;

public enum Color {
    //Color-based Themes
    RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE, GRAY, MONOCHROME, TWO_TONE, COOL_COLORS, WARM_COLORS, PSYCHEDELIC, BLACK_AND_WHITE, THREE_COLORS, WASHED_OUT, FOUR_COLORS, FIVE_COLORS, COMPLEMENTARY_COLORS, TRIADIC_COLORS, ANALOGOUS_COLORS, PASTEL, VIBRANT, MUTED, METALLIC, IRIDESCENT, BRIGHT, DARK, GLOWING, GLOW_IN_THE_DARK, GOLD, SILVER;
    public String getRarity(){
        return switch(this){
            case RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE, GRAY, TWO_TONE, COOL_COLORS, WARM_COLORS, VIBRANT, MUTED, BRIGHT, ANALOGOUS_COLORS, COMPLEMENTARY_COLORS, DARK,THREE_COLORS, TRIADIC_COLORS, FIVE_COLORS, FOUR_COLORS, GOLD, SILVER -> "NORMAL";
            case PSYCHEDELIC, MONOCHROME, IRIDESCENT, METALLIC, WASHED_OUT, PASTEL, GLOW_IN_THE_DARK -> "RARE";
            case BLACK_AND_WHITE, GLOWING -> "SUPER_RARE";
                default -> "null";
        };
    }
}
