package dev.tg;

public enum Setting {
    //General Settings and locations list
    MOUNTAIN, RIVER, FORGE, TEMPLE, UNDERWATER, DEEP_SEA, SPACE, ASTEROID, JUNGLE, FOREST, FIELD, CAVE, BARN, INDOORS, FANCY_ROOM, HOARDER_ROOM, KITCHEN, BEDROOM, BATHROOM, LIBRARY, BATH_HOUSE, HOT_SPRINGS, POOL, BILLIARDS_HALL, BOWLING_ALLEY, ARENA, SPORTS_FIELD, WATERFALL, CANYONS, CRATER, MOON, MAGICAL_REALM, CARNIVAL, GARDEN, WOODS, SPIRIT_REALM, CAVERN, UNDERGROUND_LAKE, BOAT, OCEAN, ISLAND, BEACH, HAUNTED_HOUSE, SHIPWRECK, BANK, ROCKY_BEACH, CLIFFS, DISTANT, COTTAGE, AIRPLANE, CAR, GAS_STATION, CONVENIENCE_STORE, CORN_FIELD, NEST, PARTY, ELEGANT, CYBERPUNK, STEAMPUNK, CITY, DIGITAL, ;



    public String getRarity(){
        return switch(this){
            case MOUNTAIN, RIVER, TEMPLE, UNDERWATER, SPACE, JUNGLE -> "NORMAL";
            case DEEP_SEA-> "RARE";
            case FORGE -> "SUPER_RARE";
            default -> "NORMAL";
        };
    }
}
