package dev.tg;

public enum Species {
    //Species List
    MONKEY, BEAR, BIRD, OWL, CAT, CHEETAH, JAGUAR, LION, TIGER, COW, GOAT, DOG, COYOTE, WOLF, FOX, HORSE, KANGAROO, KOALA, GIRAFFE, OPOSSUM, BADGER, FERRET, PINE_MARTEN, PANDA, RED_PANDA, RABBIT, LIZARD, SNAKE, BEAVER, MOUSE, PORCUPINE, RAT, SQUIRREL, SKUNK, KOBOLD, GRIFFIN, DEER, ALLIGATOR, POKEMON, DIGIMON, CHOCOBO, HELLHOUND, DRAGON, ELEPHANT, SHARK, BUG, OCTOPUS, FISH, PIG, HAMSTER, CHIPMUNK, PENGUIN, DONKEY, SERGAL, PROTOGEN, HUMAN, MOOGLE, LOMBAX, LLAMA, AFRICAN_WILD_DOG, CARIBOU, CHAMELEON, FENNEC, FALCON, CANINE, BORDER_COLLIE, ARCTIC_FOX, GECKO, GENET, GERMAN_SHEPHERD, HYENA, OTTER, MANED_WOLF, MEERKAT, MOOSE, OX, ORCA, OSTRICH, PANTHER, RACCOON, BUNNY, SHEEP, SLOTH, STOAT, TANUKI, TOUCAN, WALRUS, ZEBRA ;

    public String getRarity(){
        return switch (this){
            case MONKEY, BEAR, BIRD, OWL, CAT, CHEETAH, JAGUAR, LION, TIGER, COW, GOAT, DOG, COYOTE, WOLF, FOX, HORSE, KANGAROO, KOALA, OPOSSUM, BADGER, FERRET, PINE_MARTEN, PANDA, RED_PANDA, RABBIT, LIZARD, BEAVER, MOUSE, RAT, SQUIRREL, SKUNK, KOBOLD, GRIFFIN, DEER, DONKEY, LLAMA, AFRICAN_WILD_DOG, CARIBOU, CHAMELEON, FENNEC, CANINE, BORDER_COLLIE, ARCTIC_FOX, GERMAN_SHEPHERD, HYENA, OTTER, MANED_WOLF, OX, PANTHER, RACCOON, BUNNY, SHEEP -> "NORMAL";
            case ALLIGATOR, POKEMON, DIGIMON, CHOCOBO, HELLHOUND, DRAGON, PORCUPINE, GIRAFFE, PENGUIN, SHARK, PROTOGEN, MOOGLE, LOMBAX, FALCON, GECKO, GENET, MEERKAT, MOOSE, ORCA, STOAT, TANUKI, TOUCAN, ZEBRA -> "RARE";
            case ELEPHANT, BUG, OCTOPUS, FISH, PIG, HAMSTER, CHIPMUNK, SNAKE, WALRUS, SLOTH, OSTRICH, SERGAL, HUMAN -> "SUPER_RARE";
            default -> "NULL";
        };
    }
}