package dev.tg;

public enum Time {
    //List of Times of day and eras of history
    MEDIEVAL_PERIOD, ANCIENT_HISTORY, CLASSIC_ANTIQUITY, VIKING_AGE, CRUSADES, RENAISSANCE, INDUSTRIAL_REVOLUTION, VICTORIAN_ERA, SPACE_AGE, ATOMIC_AGE, GOLDEN_AGE_OF_PIRACY, FUTURE, DYSTOPIAN_FUTURE, BOUNTIFUL_OVERGROWN_FUTURE, HIGH_TECH_FUTURE, RETRO_FUTURE, EARLY_MORNING, EVENING, AFTERNOON, SUNRISE, SUNSET, MIDNIGHT;
    public String getRarity(){
        return switch(this){
            case SUNRISE, SUNSET, EVENING, AFTERNOON, EARLY_MORNING, MIDNIGHT, MEDIEVAL_PERIOD,CLASSIC_ANTIQUITY,VIKING_AGE, RENAISSANCE, INDUSTRIAL_REVOLUTION, SPACE_AGE, ATOMIC_AGE, FUTURE,DYSTOPIAN_FUTURE, RETRO_FUTURE, HIGH_TECH_FUTURE -> "NORMAL";
            case ANCIENT_HISTORY, GOLDEN_AGE_OF_PIRACY, VICTORIAN_ERA, BOUNTIFUL_OVERGROWN_FUTURE, CRUSADES -> "RARE";
//            case  -> "SUPER_RARE";
            default -> "null";
        };
    }
}
